version: '3.8'

x-my-sql-variables: &my-sql-variables
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_USERNAME: ${MYSQL_USERNAME}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
  MYSQL_HOST: ${MYSQL_HOST}
  MYSQL_PORT_OUTER: ${MYSQL_PORT_OUTER}

x-api-variables: &api-variables
  SERVER_PROTOCOL: ${SERVER_PROTOCOL}
  SERVER_HOST: ${SERVER_HOST}
  SERVER_PORT_INNER: ${SERVER_PORT_INNER}
  SERVER_PORT_OUTER: ${SERVER_PORT_OUTER}
  ACCESS_TOKEN_EXPIRED_TIME: ${ACCESS_TOKEN_EXPIRED_TIME}
  TOKEN_SECRET: ${TOKEN_SECRET}

x-client-variables: &client-variables
  CLIENT_PROTOCOL: ${CLIENT_PROTOCOL}
  CLIENT_HOST: ${CLIENT_HOST}
  CLIENT_PORT: ${CLIENT_PORT}

services:
  mysql_db:
    container_name: mysql_db
    build:
      context: ./MySQL
      target: MySQL_DB
    volumes:
      - 'mySQL_db_volume:/var/lib/mysql'
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      <<: *my-sql-variables

  api:
    container_name: api
    build:
      context: ./server
      target: api
    volumes:
      - api_volume:/app/node_modules
      - ./server:/app
    depends_on:
      - mysql_db
    ports:
      - ${SERVER_PORT_OUTER}:${SERVER_PORT_INNER}
    environment:
      <<: [*my-sql-variables, *api-variables, *client-variables]
      MYSQL_HOST_IP: mysql_db

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.0
    depends_on:
      - mysql_db
    restart: unless-stopped
    ports:
      - ${MY_SQL_ADMINER_PORT_OUTER}:80
    environment:
      PMA_ARBITRARY: 1

volumes:
  mySQL_db_volume:
  api_volume:
