export const TABLE = {
  users: 'users',
  kanban_boards: 'kanban_boards',
  kanban_columns: 'kanban_columns',
  kanban_tasks: 'kanban_tasks',
  kanban_subtasks: 'kanban_subtasks',
  kanban_task_tags: 'kanban_task_tags',
  kanban_attachments: 'kanban_attachments',
  kanban_task_attachments: 'kanban_task_attachments',
  m2m_kanban_tasks_tags: 'm2m_kanban_tasks_tags',
  m2m_kanban_users_tasks: 'm2m_kanban_users_tasks',
  folders: 'folders',
  files: 'files',
  folder_tags: 'folder_tags',
  m2m_users_folders: 'm2m_users_folders',
  m2m_folders_tags: 'm2m_folders_tags',
  user_connections: 'user_connections',
  chat_messages: 'chat_messages',
  chats: 'chats',
  genres: 'genres',
  posts: 'posts',
  m2m_users_posts_likes: 'm2m_users_posts_likes',
}
