basePath: /
definitions:
  goapi.ReportRequest:
    properties:
      description:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: something about this app
  title: NoName go_api
  version: "1.0"
paths:
  /api/books:
    get:
      consumes:
      - application/json
      description: get all books with genres and author
      produces:
      - application/json
      responses: {}
      summary: getAllBooksByGenre
      tags:
      - books
  /api/reports:
    get:
      consumes:
      - application/json
      description: get all reports
      produces:
      - application/json
      responses: {}
      summary: getAllReports
      tags:
      - report
    post:
      consumes:
      - application/json
      description: create report
      parameters:
      - description: Some description...
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/goapi.ReportRequest'
      produces:
      - application/json
      responses: {}
      summary: createReport
      tags:
      - report
  /api/reports/{id}:
    delete:
      consumes:
      - application/json
      description: delete report by id
      parameters:
      - description: Report ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: deleteReport
      tags:
      - report
    get:
      consumes:
      - application/json
      description: get report by id
      parameters:
      - description: Report ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: getReportById
      tags:
      - report
    put:
      consumes:
      - application/json
      description: update report by id
      parameters:
      - description: Report ID
        in: path
        name: id
        required: true
        type: integer
      - description: New description...
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/goapi.ReportRequest'
      produces:
      - application/json
      responses: {}
      summary: updateReport
      tags:
      - report
swagger: "2.0"
