basePath: /
host: localhost:8000
info:
  contact: {}
  description: something about this app
  title: NoName go_api
  version: "1.0"
paths:
  /go-api/authors/{id}:
    get:
      consumes:
      - application/json
      description: get author by it's id
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: getAuthorById
      tags:
      - author
  /go-api/authors/{id}/books:
    get:
      consumes:
      - application/json
      description: get all books by author id
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: getBooksByAuthorId
      tags:
      - author
  /go-api/books:
    get:
      consumes:
      - application/json
      description: get all books
      produces:
      - application/json
      responses: {}
      summary: getAllBooks
      tags:
      - books
  /go-api/books/{id}:
    get:
      consumes:
      - application/json
      description: get book by id
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: getBookById
      tags:
      - books
  /go-api/books/{id}/stats:
    get:
      consumes:
      - application/json
      description: get all books stats
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: getBookStatsById
      tags:
      - books
  /go-api/genres:
    get:
      consumes:
      - application/json
      description: get all genres
      produces:
      - application/json
      responses: {}
      summary: getAllGenres
      tags:
      - genres
  /go-api/subscribers/:
    get:
      consumes:
      - application/json
      description: get all subscribers
      produces:
      - application/json
      responses: {}
      summary: getAllSubscribers
      tags:
      - subscribers
  /go-api/subscribers/{id}:
    get:
      consumes:
      - application/json
      description: get subscriber by id
      parameters:
      - description: Subscriber ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: getSubscriberById
      tags:
      - subscribers
  /go-api/subscribtions:
    get:
      consumes:
      - application/json
      description: get all subscribtions
      produces:
      - application/json
      responses: {}
      summary: getAllSubscribtions
      tags:
      - subscribtions
swagger: "2.0"
