basePath: /
host: localhost:8000
info:
  contact: {}
  description: something about this app
  title: NoName go_api
  version: "1.0"
paths:
  /api/books:
    get:
      consumes:
      - application/json
      description: get all books with genres and author
      produces:
      - application/json
      responses: {}
      summary: getAllBooksByGenre
      tags:
      - books
  /go-api/authors/{id}:
    get:
      consumes:
      - application/json
      description: get author by it's id
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: getAuthorById
      tags:
      - author
  /go-api/authors/{id}/books:
    get:
      consumes:
      - application/json
      description: get all books by author id
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: getBooksByAuthorId
      tags:
      - author
  /go-api/genres:
    get:
      consumes:
      - application/json
      description: get all genres
      produces:
      - application/json
      responses: {}
      summary: getAllGenres
      tags:
      - genres
  /go-api/subscribtions:
    get:
      consumes:
      - application/json
      description: get all subscribtions
      produces:
      - application/json
      responses: {}
      summary: getAllSubscribtions
      tags:
      - subscribtions
swagger: "2.0"
